jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17 and Maven Central Repository
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: adopt
        java-version: '17'
        server-id: sonatype-nexus-snapshots
        server-password: MAVEN_CENTRAL_TOKEN
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      name: Cache Docker images
      uses: ScribeMD/docker-cache@0.5.0
      with:
        key: fscrawler-docker-cache-${{ runner.os }}-${{ hashFiles('pom.xml') }}
    - continue-on-error: true
      name: Build the project
      run: mvn --batch-mode install -DskipTests -Ddocker.skip
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17 and Maven Central Repository
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: adopt
        java-version: '17'
        server-id: sonatype-nexus-snapshots
        server-password: MAVEN_CENTRAL_TOKEN
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      name: Cache Docker images
      uses: ScribeMD/docker-cache@0.5.0
      with:
        key: fscrawler-docker-cache-${{ runner.os }}-${{ hashFiles('pom.xml') }}
    - continue-on-error: true
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        password: ${{ secrets.DOCKER_TOKEN }}
        username: ${{ secrets.DOCKER_USERNAME }}
    - continue-on-error: true
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      name: Deploy with Maven
      run: mvn --batch-mode deploy -DskipTests
name: Build and Deploy the master branch
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
