jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: adopt
        java-version: '17'
    - continue-on-error: true
      name: Display Maven information
      run: mvn --version
    - continue-on-error: true
      name: Build but the docker images
      run: mvn --batch-mode install -Ddocker.skip -DskipTests
  build-docker:
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: adopt
        java-version: '17'
    - continue-on-error: true
      name: Cache Docker images
      uses: ScribeMD/docker-cache@0.5.0
      with:
        key: fscrawler-docker-cache-${{ runner.os }}-${{ hashFiles('pom.xml') }}
    - continue-on-error: true
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        password: ${{ env.DOCKER_TOKEN }}
        username: ${{ env.DOCKER_USERNAME }}
    - continue-on-error: true
      name: Build the docker images
      run: mvn --batch-mode install -DskipTests
  it:
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: adopt
        java-version: '17'
    - continue-on-error: true
      name: Cache Docker images
      uses: ScribeMD/docker-cache@0.5.0
      with:
        key: fscrawler-docker-cache-${{ runner.os }}-${{ hashFiles('pom.xml') }}
    - continue-on-error: true
      name: Run the integration tests
      run: mvn --batch-mode install -Ddocker.skip -DskipUnitTests -Dtests.parallelism=1
  it-es6:
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: adopt
        java-version: '17'
    - continue-on-error: true
      name: Cache Docker images
      uses: ScribeMD/docker-cache@0.5.0
      with:
        key: fscrawler-docker-cache-${{ runner.os }}-${{ hashFiles('pom.xml') }}
    - continue-on-error: true
      name: Run the integration tests
      run: mvn --batch-mode install -Ddocker.skip -DskipUnitTests -Pes-6x -Dtests.parallelism=1
  it-es7:
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: adopt
        java-version: '17'
    - continue-on-error: true
      name: Cache Docker images
      uses: ScribeMD/docker-cache@0.5.0
      with:
        key: fscrawler-docker-cache-${{ runner.os }}-${{ hashFiles('pom.xml') }}
    - continue-on-error: true
      name: Run the integration tests
      run: mvn --batch-mode install -Ddocker.skip -DskipUnitTests -Pes-7x -Dtests.parallelism=1
  unit:
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: adopt
        java-version: '17'
    - continue-on-error: true
      name: Run all the unit tests
      run: mvn --batch-mode install -Ddocker.skip -DskipIntegTests
name: Build Pull Requests
on:
  repository_dispatch:
    types: trigger-ga___pr.yml
