jobs:
  update-files:
    if: github.event.pull_request.base.repo.full_name == github.event.pull_request.head.repo.full_name
    permissions:
      contents: write
      packages: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        token: ${{ secrets.PAT || github.token }}
    - continue-on-error: true
      name: Update resources with Maven
      run: mvn -B  generate-resources
    - continue-on-error: true
      name: Update files if needed
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: Automatically update versions
name: Update Pull Requests files
on:
  repository_dispatch:
    types: trigger-ga___update-files.yml
